export const ADD_ITEM_MENU = "ADD_ITEM_MENU";
export const MODIFICA_DISPLAY = "MODIFICA_DISPLAY";
export const MODIFICA_TEMA = "MODIFICA_TEMA";
export const SET_ATRIBUTO = "SET_ATRIBUTO";
export const SET_ATRIBUTO_MENU = "SET_ATRIBUTO_MENU";
export const AUTENTICA = "AUTENTICA";
export const SET_USERNAME = "SET_USERNAME";